version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - MEDIA_PATH:/Music
      - MISSING_COVER_ART_PATH:/missing_cover_art
      - CONFIG_PATH:/Config
    environment:
      - BACKEND_PORT=3001
      - NEXTAUTH_SECRET=SALKDNAKFB@!WQ#
      - NEXTAUTH_URL=http://localhost:3000
      - NODE_ENV=production
      - DEPLOYMENT_TYPE=docker
  backend:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - MEDIA_PATH:/Music
      - MISSING_COVER_ART_PATH:/missing_cover_art
      - CONFIG_PATH:/Config
