services:
  music-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parsonlabs-music
    ports:
      - "1993:1993"
    volumes:
      - "/path/to/config:/ParsonLabsMusic"
      - "/path/to/music:/music"
    restart: unless-stopped