# Dockerfile for Rust
FROM rust:1.56 as builder
WORKDIR /usr/src

# Copy your source code
COPY ./apps/web/backend /usr/src/backend
WORKDIR /usr/src/backend

# Build the application
RUN cargo build --release

# Start a new stage
FROM debian:buster-slim
COPY --from=builder /usr/src/backend/target/release/backend /usr/local/bin

# Run the binary
CMD ["backend"]