# Dockerfile for Rust
FROM rust:latest as builder
WORKDIR /usr/src

# Copy your source code
COPY ./apps/web/backend /usr/src/backend
WORKDIR /usr/src/backend

# Build the application
RUN cargo build --release

# Start a new stage
FROM debian:bullseye-slim

# Install libssl
RUN apt-get update && apt-get install -y libssl1.1 && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/backend/target/release/music-backend /usr/local/bin

# Run the binary
CMD ["music-backend"]