# Dockerfile for Rust
FROM rust:1-alpine as builder
WORKDIR /usr/src

# Copy your source code
COPY ./apps/web/backend /usr/src/backend
WORKDIR /usr/src/backend

RUN apk add --no-cache libressl-dev musl-dev

# Build the application
RUN cargo build --release

# Start a new stage
FROM alpine

RUN apk add --no-cache libressl-dev

COPY --from=builder /usr/src/backend/target/release/music-backend /usr/local/bin

# Run the binary
CMD ["music-backend"]