name: "Check Server"

on:
  push:
  pull_request:

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: Install NASM
        run: sudo apt-get update && sudo apt-get install -y nasm
      - name: Create necessary folders
        run: mkdir -p apps/web/out
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy,rustfmt
          cache: true
          cache-on-failure: true
          matcher: true
          rustflags: ""
      - run: cargo check -p music-server