name: Publish Latest Version to Container Registry

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host

    - name: Set short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/willkirkmanm/music:latest
          ghcr.io/willkirkmanm/music:${{ steps.vars.outputs.sha_short }}
        cache-from: |
          type=registry,ref=ghcr.io/willkirkmanm/music:buildcache
        cache-to: |
          type=local,dest=/tmp/.buildx-cache