name: Web Type Check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            apps/web/node_modules
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/package.json', '**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Prepare environment
        run: |
          echo "::group::Node environment info"
          node --version
          npm --version
          echo "::endgroup::"
          
          echo "::group::Prepare esbuild dependencies"
          npm install -g esbuild@0.21.1
          export ESBUILD_BINARY_PATH=$(which esbuild)
          echo "ESBUILD_BINARY_PATH=$ESBUILD_BINARY_PATH" >> $GITHUB_ENV
          echo "::endgroup::"
      
      - name: Install root dependencies
        run: |
          export ESBUILD_SKIP_POSTINSTALL=1
          export ESBUILD_BINARY_PATH=$(which esbuild)
          bun install

      - name: Install web dependencies
        run: |
          export ESBUILD_SKIP_POSTINSTALL=1
          export ESBUILD_BINARY_PATH=$(which esbuild)
          bun install
        working-directory: apps/web
        env:
          BUN_INSTALL_SKIP_DOWNLOAD: "true"

      - name: Run type-check
        run: bun run type-check
        working-directory: apps/web
        env:
          ESBUILD_BINARY_PATH: ${{ env.ESBUILD_BINARY_PATH }}
